name: Docs
on:
  push:
    branches:
      - master
    # TODO: Keep all historical builds (like the js-sdk)
    #tags: ['v*']
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn install
    - run: yarn docs
    - name: Build and deploy docs
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: .jsdoc/matrix-bot-sdk/develop
